version: '3.7'
services:
  eventcache:
    image: redis:6.0-alpine
    ports:
      - 6379:6379
    volumes:
      - ./conf/redis.conf:/usr/local/etc/redis/redis.conf
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
  eventbus:
    image: rabbitmq:3.8
    ports:
      - 5672:5672
  eventmanager:
    build: .
    depends_on:
      - eventbus
    command: sh -c "/wait && /eventmanager/eventmanager"
    environment:
      WAIT_HOSTS: eventbus:5672
      WAIT_HOSTS_TIMEOUT: 30
      WAIT_SLEEP_INTERVAL: 10
      WAIT_HOST_CONNECT_TIMEOUT: 30
      WAIT_LOGGER_LEVEL: debug
      EV_CACHE: redis://eventcache:6379/0
      EV_BUS: amqp://guest:guest@eventbus:5672/
    ports:
      - 9999:9999



